version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install flask

  pre_build:
    commands:
      - echo Pre-build phase started

  build:
    commands:
      - echo Build phase started
      - echo Nothing to build for Flask app

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
